name: Python Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Code format check with Black
        run: |
          black --check day5/演習3

      - name: Test with pytest
        run: |
          pytest day5/演習3/tests/ -v
